import { z } from "zod";

export const vinyleSchema = z.object({
    artist: z.string().min(1, "Champ requis"),
    title: z.string().min(1, "Champ requis"),
    support: z.string().min(1, "Champ requis"),
    countryYear: z.string().min(1, "Champ requis"),
    buyPlace: z.string().min(1, "Champ requis"),
    netBuyPrice: z.coerce.number().nonnegative("Doit être positif"),
    buyDate: z.string().min(1, "Champ requis"),
    sellingStatus: z.string().min(1, "Champ requis"),
    diskCondition: z.string().min(1, "Champ requis"),

    label: z.string().nullable().optional(),
    genre: z.string().nullable().optional(),
    notes: z.string().nullable().optional(),
    sellingPlace: z.string().nullable().optional(),
    sellingDate: z.string().nullable().optional(),
    netSellingPrice: z.coerce.number().nullable().optional(),
    buyDeliveryFees: z.coerce.number().nullable().optional(),
    sellingDeliveryFees: z.coerce.number().nullable().optional(),
    sellingCommission: z.coerce.number().nullable().optional(),
    paypalFees: z.coerce.number().nullable().optional(),
    iebayFees: z.coerce.number().nullable().optional(),
    paymentStatus: z.string().nullable().optional(),
    deliveryStatus: z.string().nullable().optional(),
    isReceived: z.string().nullable().optional(),
    scanStatus: z.string().nullable().optional(),
    ref: z.string().nullable().optional(),
    cdlpListingPrice: z.coerce.number().nullable().optional(),
    cdlpListingStatus: z.string().nullable().optional(),
    discogsSellingPrice: z.coerce.number().nullable().optional(),
    discogsSellingStatus: z.string().nullable().optional(),
    listingIssues: z.string().nullable().optional(),
    ebayListingStatus: z.string().nullable().optional(),
});


export type VinyleFormData = z.infer<typeof vinyleSchema>;

export const requiredFields: (keyof VinyleFormData)[] = [
    "artist",
    "title",
    "support",
    "countryYear",
    "buyPlace",
    "netBuyPrice",
    "buyDate",
    "sellingStatus",
    "diskCondition",
];

export const orderedFields: (keyof VinyleFormData)[] = [
    "artist",
    "title",
    "support",
    "genre",
    "label",
    "countryYear",
    "ref",
    "diskCondition",
    "scanStatus",
    "notes",
    "buyDate",
    "buyPlace",
    "netBuyPrice",
    "buyDeliveryFees",
    "sellingStatus",
    "sellingPlace",
    "sellingDate",
    "netSellingPrice",
    "sellingDeliveryFees",
    "sellingCommission",
    "paypalFees",
    "iebayFees",
    "paymentStatus",
    "deliveryStatus",
    "isReceived",
    "cdlpListingPrice",
    "cdlpListingStatus",
    "discogsSellingPrice",
    "discogsSellingStatus",
    "ebayListingStatus",
    "listingIssues",
];
